import enum


class Role(str, enum.Enum):
    STUDENT = "STUDENT"
    HOD = "HOD"
    WARDEN = "WARDEN"
    WATCHMAN = "WATCHMAN"


class OutingStatus(str, enum.Enum):
    PENDING_HOD = "PENDING_HOD"
    PENDING_WARDEN = "PENDING_WARDEN"
    PENDING_WARDEN_ASSIGNMENT = "PENDING_WARDEN_ASSIGNMENT"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    CANCELLED = "CANCELLED"
    EXITED = "EXITED"
    COMPLETED = "COMPLETED"
    LATE_RETURN = "LATE_RETURN"



class ApprovalAction(str, enum.Enum):
    SUBMITTED = "SUBMITTED"
    HOD_APPROVED = "HOD_APPROVED"
    HOD_REJECTED = "HOD_REJECTED"
    WARDEN_APPROVED = "WARDEN_APPROVED"
    WARDEN_REJECTED = "WARDEN_REJECTED"
    PARENT_APPROVAL_CONFIRMED = "PARENT_APPROVAL_CONFIRMED"
    CANCELLED = "CANCELLED"
    EXIT_RECORDED = "EXIT_RECORDED"
    RETURN_RECORDED = "RETURN_RECORDED"
    LATE_RETURN_DETECTED = "LATE_RETURN_DETECTED"
    COMPLETED = "COMPLETED"


class GateStatus(str, enum.Enum):
    EXIT_RECORDED = "EXIT_RECORDED"
    RETURN_RECORDED = "RETURN_RECORDED"
    COMPLETED = "COMPLETED"
    LATE_RETURN = "LATE_RETURN"
